// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consensus "github.com/thep2p/go-eth-localnet/internal/consensus"
)

// MockLauncher is an autogenerated mock type for the Launcher type
type MockLauncher struct {
	mock.Mock
}

type MockLauncher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLauncher) EXPECT() *MockLauncher_Expecter {
	return &MockLauncher_Expecter{mock: &_m.Mock}
}

// Launch provides a mock function with given fields: cfg
func (_m *MockLauncher) Launch(cfg consensus.Config) (consensus.Client, error) {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Launch")
	}

	var r0 consensus.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(consensus.Config) (consensus.Client, error)); ok {
		return rf(cfg)
	}
	if rf, ok := ret.Get(0).(func(consensus.Config) consensus.Client); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consensus.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(consensus.Config) error); ok {
		r1 = rf(cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLauncher_Launch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Launch'
type MockLauncher_Launch_Call struct {
	*mock.Call
}

// Launch is a helper method to define mock.On call
//   - cfg consensus.Config
func (_e *MockLauncher_Expecter) Launch(cfg interface{}) *MockLauncher_Launch_Call {
	return &MockLauncher_Launch_Call{Call: _e.mock.On("Launch", cfg)}
}

func (_c *MockLauncher_Launch_Call) Run(run func(cfg consensus.Config)) *MockLauncher_Launch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consensus.Config))
	})
	return _c
}

func (_c *MockLauncher_Launch_Call) Return(_a0 consensus.Client, _a1 error) *MockLauncher_Launch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLauncher_Launch_Call) RunAndReturn(run func(consensus.Config) (consensus.Client, error)) *MockLauncher_Launch_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockLauncher) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockLauncher_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockLauncher_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockLauncher_Expecter) Name() *MockLauncher_Name_Call {
	return &MockLauncher_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockLauncher_Name_Call) Run(run func()) *MockLauncher_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLauncher_Name_Call) Return(_a0 string) *MockLauncher_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLauncher_Name_Call) RunAndReturn(run func() string) *MockLauncher_Name_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConfig provides a mock function with given fields: cfg
func (_m *MockLauncher) ValidateConfig(cfg consensus.Config) error {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for ValidateConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(consensus.Config) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLauncher_ValidateConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConfig'
type MockLauncher_ValidateConfig_Call struct {
	*mock.Call
}

// ValidateConfig is a helper method to define mock.On call
//   - cfg consensus.Config
func (_e *MockLauncher_Expecter) ValidateConfig(cfg interface{}) *MockLauncher_ValidateConfig_Call {
	return &MockLauncher_ValidateConfig_Call{Call: _e.mock.On("ValidateConfig", cfg)}
}

func (_c *MockLauncher_ValidateConfig_Call) Run(run func(cfg consensus.Config)) *MockLauncher_ValidateConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consensus.Config))
	})
	return _c
}

func (_c *MockLauncher_ValidateConfig_Call) Return(_a0 error) *MockLauncher_ValidateConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLauncher_ValidateConfig_Call) RunAndReturn(run func(consensus.Config) error) *MockLauncher_ValidateConfig_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLauncher creates a new instance of MockLauncher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLauncher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLauncher {
	mock := &MockLauncher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
