// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	consensus "github.com/thep2p/go-eth-localnet/internal/consensus"

	modules "github.com/thep2p/skipgraph-go/modules"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// BeaconEndpoint provides a mock function with no fields
func (_m *MockClient) BeaconEndpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BeaconEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockClient_BeaconEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeaconEndpoint'
type MockClient_BeaconEndpoint_Call struct {
	*mock.Call
}

// BeaconEndpoint is a helper method to define mock.On call
func (_e *MockClient_Expecter) BeaconEndpoint() *MockClient_BeaconEndpoint_Call {
	return &MockClient_BeaconEndpoint_Call{Call: _e.mock.On("BeaconEndpoint")}
}

func (_c *MockClient_BeaconEndpoint_Call) Run(run func()) *MockClient_BeaconEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_BeaconEndpoint_Call) Return(_a0 string) *MockClient_BeaconEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_BeaconEndpoint_Call) RunAndReturn(run func() string) *MockClient_BeaconEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Done provides a mock function with no fields
func (_m *MockClient) Done() <-chan interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Done")
	}

	var r0 <-chan interface{}
	if rf, ok := ret.Get(0).(func() <-chan interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan interface{})
		}
	}

	return r0
}

// MockClient_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockClient_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
func (_e *MockClient_Expecter) Done() *MockClient_Done_Call {
	return &MockClient_Done_Call{Call: _e.mock.On("Done")}
}

func (_c *MockClient_Done_Call) Run(run func()) *MockClient_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Done_Call) Return(_a0 <-chan interface{}) *MockClient_Done_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Done_Call) RunAndReturn(run func() <-chan interface{}) *MockClient_Done_Call {
	_c.Call.Return(run)
	return _c
}

// Metrics provides a mock function with no fields
func (_m *MockClient) Metrics() (*consensus.Metrics, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metrics")
	}

	var r0 *consensus.Metrics
	var r1 error
	if rf, ok := ret.Get(0).(func() (*consensus.Metrics, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *consensus.Metrics); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*consensus.Metrics)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_Metrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metrics'
type MockClient_Metrics_Call struct {
	*mock.Call
}

// Metrics is a helper method to define mock.On call
func (_e *MockClient_Expecter) Metrics() *MockClient_Metrics_Call {
	return &MockClient_Metrics_Call{Call: _e.mock.On("Metrics")}
}

func (_c *MockClient_Metrics_Call) Run(run func()) *MockClient_Metrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Metrics_Call) Return(_a0 *consensus.Metrics, _a1 error) *MockClient_Metrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_Metrics_Call) RunAndReturn(run func() (*consensus.Metrics, error)) *MockClient_Metrics_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function with no fields
func (_m *MockClient) Ready() <-chan interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 <-chan interface{}
	if rf, ok := ret.Get(0).(func() <-chan interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan interface{})
		}
	}

	return r0
}

// MockClient_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockClient_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockClient_Expecter) Ready() *MockClient_Ready_Call {
	return &MockClient_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *MockClient_Ready_Call) Run(run func()) *MockClient_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Ready_Call) Return(_a0 <-chan interface{}) *MockClient_Ready_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Ready_Call) RunAndReturn(run func() <-chan interface{}) *MockClient_Ready_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockClient) Start(ctx modules.ThrowableContext) {
	_m.Called(ctx)
}

// MockClient_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockClient_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx modules.ThrowableContext
func (_e *MockClient_Expecter) Start(ctx interface{}) *MockClient_Start_Call {
	return &MockClient_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockClient_Start_Call) Run(run func(ctx modules.ThrowableContext)) *MockClient_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(modules.ThrowableContext))
	})
	return _c
}

func (_c *MockClient_Start_Call) Return() *MockClient_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Start_Call) RunAndReturn(run func(modules.ThrowableContext)) *MockClient_Start_Call {
	_c.Run(run)
	return _c
}

// ValidatorKeys provides a mock function with no fields
func (_m *MockClient) ValidatorKeys() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidatorKeys")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockClient_ValidatorKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatorKeys'
type MockClient_ValidatorKeys_Call struct {
	*mock.Call
}

// ValidatorKeys is a helper method to define mock.On call
func (_e *MockClient_Expecter) ValidatorKeys() *MockClient_ValidatorKeys_Call {
	return &MockClient_ValidatorKeys_Call{Call: _e.mock.On("ValidatorKeys")}
}

func (_c *MockClient_ValidatorKeys_Call) Run(run func()) *MockClient_ValidatorKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ValidatorKeys_Call) Return(_a0 []string) *MockClient_ValidatorKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_ValidatorKeys_Call) RunAndReturn(run func() []string) *MockClient_ValidatorKeys_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
