name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        go-version: [ '1.23' ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Restore Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            # Don't cache bin/ !
            # Don't cache bin/solc !
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build the code
        run: make build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.10

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.64.5/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.64.5

      - name: Lint the code
        run: $GITHUB_WORKSPACE/bin/golangci-lint run --config integration/golangci-lint.yml ./...

  unittest:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.23' ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Solidity 0.8.30+commit.73712a01
        run: |
          set -e
          SOLC_VERSION=0.8.30
          SOLC_COMMIT=73712a01
          mkdir -p ./bin
          # Try static binary first (does NOT exist for this version)
          SOLC_URL="https://github.com/ethereum/solidity/releases/download/v${SOLC_VERSION}+commit.${SOLC_COMMIT}/solc-static-linux"
          HTTP_STATUS=$(curl -sSL -w '%{http_code}' -o ./bin/solc "$SOLC_URL")
          if [ "$HTTP_STATUS" != "200" ]; then
            # Fallback to .tar.gz
            SOLC_URL="https://github.com/ethereum/solidity/releases/download/v${SOLC_VERSION}+commit.${SOLC_COMMIT}/solc.tar.gz"
            echo "Static binary not found, falling back to tar.gz: $SOLC_URL"
            curl -sSL -o ./bin/solc.tar.gz "$SOLC_URL"
            tar -xzvf ./bin/solc.tar.gz -C ./bin
          fi
          chmod +x ./bin/solc
          echo "$(pwd)/bin" >> $GITHUB_PATH
          ./bin/solc --version
      - name: Run tests
        run: make test
