name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: true
      matrix:
        go-version: [ '1.23' ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Restore Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            # Don't cache bin/ !
            # Don't cache bin/solc !
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Build the code
        run: make build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.10

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.64.5/install.sh | sh -s -- -b $GITHUB_WORKSPACE/bin v1.64.5

      - name: Lint the code
        run: $GITHUB_WORKSPACE/bin/golangci-lint run --config integration/golangci-lint.yml ./...

  unittest:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.23' ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Go-solc-select
        run: |
          go install github.com/fabelx/go-solc-select/cmd/gsolc-select@latest
      - name: Install and use Solidity 0.8.30
        run: |
          set -e
          gsolc-select install 0.8.30
          gsolc-select use 0.8.30 || (echo "gsolc-select failed; check formatting in its output"; exit 1)
          export PATH="$HOME/.solc-select/bin:$PATH"
          which solc
          solc --version
      - name: Add solc-select to PATH for later steps
        run: |
          echo "$HOME/.solc-select/bin" >> $GITHUB_PATH
      - name: Run tests
        run: make test
